### PR TITLE
Add Django 2.0 support

### PR DESCRIPTION
**Pull request by iancubitt**

### CODE REVIEW

**Comment by BarnabasSzabolcs** [comment]
actually this should be the other way around. It works with "from django.urls import reverse, NoReverseMatch" since Django 1.10.

**Comment by iancubitt** [comment]
Hello, it first tries to import from the old location for older Django versions and then if the ImportError is raised we import from the new location for more recent Django versions. The old location was only deprecated in Django 1.10, it was not removed until Django 2. I made this quick pull request to fix the Django 2 compatibility issue whilst maintaining backwards compatibility with older versions of Django. I guess it could be swapped around to try to import from the new location first but behaviourally it shouldn't matter. In any case unfortunately over 6 months later this hasn't been merged and no other update for Django 2 compatibility has been implemented either.

**Comment by xaralis** [comment]
Sorry guys. Merging now.

**Comment by xaralis** [comment]
Released as https://github.com/xaralis/django-static-sitemaps/releases/tag/4.5.0

**Pull request merged**
